import os
import re

GLOSSARIES = {
    # MIC SERIES (6 to 10)
    "mic6": {
        "color": "indigo",
        "title": "Glosario de Microeconomía",
        "concepts": [
            ("Oligopolio", "Estructura intermedia e imperfecta de tensión asfixiante donde un puñado excluyente y selecto de corporaciones colosales acapara la dictadura oferente. Sus determinaciones resolutivas (precios $P$ o volúmenes $Q$) no son aisladas ni asintóticas, sino que detonan repercusiones y contramedidas cruzadas vengativas colaterales o empatías tácticas (interdependencia estratégica) en sus pocos rivales supervivientes."),
            ("Cartel", "Sindicación o entramado mafioso colusorio táctico y amurallado explícito donde la trinidad u oligopolistas claudican a su hostilidad sangrienta competencial para fusionarse utópica y clandestinamente en un ente supra-corporativo emulando la dictadura absolutista de un Monopolio puro, pactando y seccionando cuotas inelásticas y encareciendo asfixiantemente los márgenes $P$ extorsionando al mercado unificado."),
            ("Equilibrio de Nash", "Punto de fuga estancado y resolución empantanada lógicamente irresoluble praxeológica de la Teoría de Juegos. Es la intersección paralizante donde ningún estratega u oligopolista, conociendo retrospectivamente y prefigurando la inamovible hostil o pacífica decisión del rival, encuentra incentivo, lucro marginal o salvación individual alguna en desviarse unilateralmente o traicionar su postura tomada sin inmolarse."),
            ("Dilema del Prisionero", "Alegoría sociológica y matriz letal de sub-optimización donde la racionalidad pura calculadora avariciosa egoísta inescrutable y desconfiada de individuos escindidos los condena ineludible e inexorablemente a claudicar y encallarse en la traición mutua y peor condena (subóptimo de Pareto) lapidando la redentora salvación cooperativa colectivista que, aunque utópicamente idónea y superior, los exalta asimétricamente a riesgos letales de engaño aniquilador."),
            ("Liderazgo en Precios (Stackelberg)", "Asimetría temporal e imperiosa en oligopolios o arenas de juego donde un coloso pionero o alfa corporativo estipula, golpea, enarbola o ancla anticipada y primero unilateralmente sus vectores u ofertas, forzando coartantemente a la comparsa de seguidores dóciles pasivos o subyugados a acomodarse, internalizar y pivotar constreñidamente sus lógicas reaccionarias a merced del dictamen inamovible ya pre-jugado del líder imperante.")
        ]
    },
    "mic7": {
        "color": "indigo",
        "title": "Glosario de Microeconomía",
        "concepts": [
            ("Riesgo Moral (Moral Hazard)", "Falla abismal e infección prebendarista de arquitecturas asimétricas informacionales gestada post-contratación. El asegurado o agente delegado endógeno, habiéndose agenciado de escudos y garantías inmunizadoras blindadas por un principal ciego protector, muta su accionar perversamente relajando cuidados redentores incurriendo u arriesgando imprudente irracional temeraria extorsiva indolente o azarosamente sabiendo inescrutable su externalización eximente de toda purga castigadora punitiva ruinosa trasladándola y vampirizándola íntegramente deudas o expiaciones a las tesorerías lumbares del asegurador ciego e impotente indemnizador paralítico subsidiante y desvalijado redentor ineficiente."),
            ("Selección Adversa", "Infección y metástasis parasitaria corroyente estigmatizante de mercados asimétricamente nublados dislocados y pre-contractuales opacos donde la fracción indeseada estropeada devaluada nociva maculada riesgosa patológica defectuosa mermada estropeada encubierta y perversa (ej: limones cacharros o adictos terminales silentes engañosos desahuciados patológicos) expulsa excluyentamente canibalizando letal implacablemente agigantándose aniquilando e invisibilizando al porcentaje benévolo puro sano e incólume, arruinando colapsando asolando vaciando el ecosistema abismadoramente desfondando y paralizándolo liquidandolo asfixiando transacciones plenas simétricas justas."),
            ("Problema del Principal-Agente", "Dicotomía trágica irresoluble en matrices organizativas capitalistas divorciándose la titularidad de la praxis empírica operaria. Los propósitos utilitaristas altruistas corporativos capitalizadores supremos del amo financiador (Principal) colisionan despóticamente antagónicas y esquizofrénicas inelásticas irreparables desviándose frente a las pulsiones expoliadoras avariciosas vacacionistas de holgazanerías cortoplacistas expoliadoras parasitarias expropiadoras encubiertas egoístas frívolas fútiles del delegado y rentado lugarteniente testaferro o peón mánager ejecutivo (Agente), exigiéndole monitoreos extenuantes asfixiantes gravosos policiales carísimos paralizantes coactivos punitorios represivos."),
            ("Señalización (Signaling)", "Mecanoreceptor paliativo salvataje o faro clarificador deslumbrante irrumpido por la facción pura aventajada del mercado opacado perverso. Para escindirse irrefutable destacarse asimétrica comprobable e inescrutable asintótica del vulgo degradado defectuoso falsificable mentiroso engañoso inferior o simulador patológico, el virtuoso inmola sacrifica invierte asumiendo quemaduras ostentosas de riquezas diplomas colosales publicitarias o garantías irrenunciables tan exorbitantes costosísimas exclusivas imposibles inalcanzables astronómicas abisales y empobrecedoras suicidas que un impostor fútil simulador estafador inoperante perdedor marginal defectuoso jamás emularía costear sin quebrar, purificando redimiendo clarificando y desnudando indiscutible la asimetría oculta revelando su real estatus subyacente prístino selecto."),
            ("Filtrado (Screening)", "Aspiradora de testeo o colador inquisitorio perenne esgrimida despóticamente pero inquisitivamente inteligente y salvadora por la cohorte ciega principalista desvalida estafada o empleadora desahuciada. Diseñan menús retorcidos encrucijadas de elección discriminadoras test empíricos auto-reveladores ineludibles sutiles subyacentes o seguros auto-deducibles asimiladores que obligan subrepticia indomeñablemente inescrutable y coactivamente a la multitud enigmática aglomerada a desenmascararse revelando clasificándose por sus actos resolutivos descifrando asimétrica y segregando desnudando su verdadera matriz estirposa oculta interior praxeológica y purificando la ceguera contractual redentora empírica decodificadora desmitificadora resolutoria salvajemente eficaz infalible expósita.")
        ]
    },
    "mic8": {
        "color": "indigo",
        "title": "Glosario de Microeconomía",
        "concepts": [
            ("Equilibrio General", "Cúspide inmaculada paramétrica euclídea y arquitectura suprema holística y totalizante cénit de Walras donde la infinidad inescrutable astronómica incesante colosal multiplicidad atomizada interdependiente de millones de ecosistemas subyacentes mercantiles plazas laberínticas se concatenan vaciándose inelásticas e irreductiblemente purificadas simultánea y milimétricamente plenas intersectando estáticas vaciadoras sinérgicas simbióticas de compensaciones P y Q interconectadas unánimes globalizadas estabilizadas absolutistas eximiendo dislocaciones residuales."),
            ("Caja de Edgeworth", "Recinto gráfico claustro y mapa topográfico cuadrangular bidimensional inmaculado analógico para diagramar la colisión simbiótica bilateral cruda y la arena resolutiva de dos agentes exógenos canjeando una dotación fija finita inelástica amurallada prefabricada inalterable estática y agotable de dos puros bienes, interceptándose en laberintos topográficos de compensaciones hicksianas y revelando ineludibles negociaciones."),
            ("Óptimo de Pareto", "Estado celestial clímax supremo intocable e irreductible resolutivo y distributivo dictaminador dogmático paralizador donde ya cualquier ingeniería de transmutación mudanza o expropiatoria recanalización asimétrica de riquezas o cuotas redistributivas expoliadoras transaccionales que ose engrosar u optimizar compensaciones a un ciudadano enaltecido derivará forzosa punitiva trágica letal e ineluctablemente inexorable y sin resguardo en el hundimiento merma destitución pauperización amputación y flagelo expropiador devorador asfixiante irremediable del bienestar utilitarista del vecino marginado adyacente en la red."),
            ("Curva de Contrato", "Cordillera topográfica y espina dorsal estática inamovible de la Caja de Edgeworth engarce aglutinando e interconectando tangencial resolutiva todas plenas incontables inifinitas asignaciones eficientes inmaculadas óptimas supremas paretianas donde las laderas cóncavas RMS de los bandos litigantes en la arena empatan plenas asintóticas clónicas neutralizantes compensadoras matemáticas."),
            ("Teoremas del Bienestar", "Dogmas capitales y epifanías matemáticas subyacentes cardinales inescrutables de la economía teorética puros: 1° Que toda arcadia competitiva libre de impurezas y opacidades encabrita ineludiblemente resolviéndose empíricamente decantando arrastrada de mercado decantándose invariablemente un clímax Pareto Eficiente absoluto puro e incondicionado; y 2° Que si re-orquestas expropiantemente dictatorial las herencias dotacionales originarias, un mercado puro libre puede re-vaciarse encauzándose a estabilizar milagrosamente asintótico empíricamente cualquier deseado anhelo equitativo punto paretiano social utópico dictaminado.")
        ]
    },
    "mic9": {
        "color": "indigo",
        "title": "Glosario de Microeconomía",
        "concepts": [
            ("Externalidad", "Infección, onda expansiva desatada o secuela colateral residual implacable y esquirlar fugada exenta u omitida subrepticiamente letal o beneficiosa del corset de precios transaccional tarifado contabilizado, impactando percutiendo bendiciendo fertilizante o lacerando castigadora amputando irremediablemente la hacienda salud pulmones o haberes cívicos de terceros adyacentes inertes excluidos ajenos no inmersos voluntarios en el contrato transaccional bilateral focal."),
            ("Pigou (Impuesto/Subsidio)", "Ingeniería exógena estatal quirúrgica expropiatoria o inyectiva monetaria de peajes e impuestos correctivos recargados amputativos o subsidios compensadores aliviadores dictaminada autocráticamente inyectiva inescrutable y calibrada impositivamente ex-ante para encarecer disuasorio asfixiante o abaratando asimilable acoplada calco fidedigna exacta milimétrica espejada al costo punitivo trágico o al goce providencial inintencionado desbocado y escindido fugitivo de la externalidad subyugante marginada."),
            ("Teorema de Coase", "Acertijo revolucionario mitigador anarcoliberal estipulando que si las actas matrices originarias expropiatorias titulaciones y derechos fácticos propietarios de propiedad cruda e irrestricta subyacente yerran delimitadas cristalinas inquebrantables irrevocables pre-asignadas inobjetables estipuladas y los rozamientos burocráticos costes litigantes legales interinos transaccionales operantes exógenos mutuos friccionales resolutivos son inexistentes irrisorios estériles o infinitesimales irrisorios nulos abismales asintóticos a cero; el ecosistema pactante de individuos plebeyos colindantes resolverá y pactará resarcimientos internos asimétricos negociables aniquilando esfumando la secuela ineficiente internalizándola endógena resolviéndola inmaculada redentora pareto-eficiente siempre invariablemente inmune sin injerencia ajena absolutista inoperante exógena estatista intrometida burócrata dictaminadora paternal."),
            ("Bienes Públicos", "Entidades supra-mercantiles conceptuales estigmatizadas u ofertadas exentas y despojadas ontológicamente empíricas y naturales puritanas absolutas de rivalidad destructiva excluyente y de exclusión peajera segregacionista barrera amurallada (ej: faros navales luminarias o milicias fronterizas). Si alguien exprime o recaba la gracia usufructora no desgasta roe o margina ni en fracciones menguantes el goce adyacente intacto de sus conciudadanos y simultáneamente es quimérica operante inviable imposible restringir aduaneramente o arancelariamente asfixiatoria su lluvia providencial benéfica a réprobos o polizones esquivadores de cuotas tributarias retributivas evasores morosos elusores crudos."),
            ("Tragedia de los Comunes", "Destino fatídico fútil holocausto dantesco letal y depredación canibalizadora voraz apocalíptica irremediable colosal y aniquiladora de acervos biológicos recursos o patos indivisos praderas inagotables en apariencia pero vaciables explotables (bienes comunes carentes exentos de amuralla alambrado propietario ineluctable barrera expropiable defensiva). El egoísmo ciego cortoplacista exultante predador asimétrico maximizador irreflexivo frívolo subyugante de las muchedumbres pastorales sin dueño succiona expolia exaurie arranca extingue aniquiladora sobreexplotando el vergel desértico exterminando y esquilmando arruinando colapsando y deforestando exterminadora la cuenca desolando empírica la fuente matriz madre aniquilando desabastecedora irremisible asolando perenne el recurso desfondando desolando para el devenir trágico universal fútil aniquilante asimilador colapsante colosal agobiador terminal infructuoso asolador y extintivo.")
        ]
    },
    "mic10": {
        "color": "indigo",
        "title": "Glosario de Microeconomía",
        "concepts": [
            ("Mecanismo de Subasta", "Protocolos ingenieriles arquitecturas de licitación subyacentes y arenas resolutorias pre-ensayadas artificiales de puja canónica acaparadora destiladoras extractivas asimétricas empedernidas e inquisidoras para rematar acervos raros o concesiones estatales donde la meta utilitarista del rematador expropiador maximizador no es meramente claudicar la cosa final adjudicadora asintótica sino extraer extirpar desnudar arrancar abismal subrepticia y empíricamente exprimir asfixiantemente inquisitiva ex-post implacable inescrutable estrujar dictatorial subyugando extorsiva el valor e inmenso anhelo oculto hermético inescrutable subjetivo resguardado opaco silenciado predispuesto celosamente inconfensable del rematante y bolsillos del adjudicatario estrujando y drenando asimilándole y arrebatándole su renuente escondida colosal y máxima renuente fáctica inconfesa ineluctable y velada valoración cruda."),
            ("Subasta Inglesa", "Liturgia teatral rematadora en escalada exultante viva aural ascendente coral donde las proferencias pujan incesantes desafiantes agigantando en estentóreas sobrepujas crecientes abismadoras desatadas el umbral P hasta destilar marginar diezmar ahogar espantar excluir e inhabilitar desbancar asfixiar desplomar y desfondar exhaustivamente a todos los lidiadores competentes contendientes acorralados cediendo la victoria y excedentario al último estoico sobreviviente titán impasible asimilado."),
            ("Subasta Holandesa", "Inquisición inversa tensa aural cronómetro depresivo fútil descendente agónico licuador vertiginosa y de pánico relámpago ineluctable precipitando precios exultantes abismales estrafalarios exorbitantes en picada asfixiante declinante licuacionista asimétrica ferial hasta que el inaguantable silencio asimilador se quiebra por un postor desesperado claudicando precipitado rompiendo el vacío aterrorizado aterrorizante de extraviar perder el lote parando frenando y asimilando el reloj anclando asimétrica su precio victorioso y acaparador."),
            ("Maldición del Ganador", "Resaca fatal inmoladora tragedia y escarmiento letal pírrico castigador ex-post del victorioso exultante rematador en subastas de lotes de valores ignotos o hidrocarburos ciegos yacimientos inescrutables empíricos opacos objetivos subyacentes donde, al adjudicarse la plaza, infiere aterrorizadamente abismal y dolorosamente desoladora y certera innegable fútilmente abismadora y colosalmente que su tasación inusitada ganadora fue la más desvariada absurda irracional descabellada y distorsionada optimista asintótica de la manada encumbrada exacerbada y distorsionada sobreestimada perdiendo y quemando irremediablemente expropiando asfixiado rentabilidades fútiles asimilando su ruinosa inmersión quebrando abismada y destartaladamente abultada ruina o pérdida implacable."),
            ("Diseño de Mecanismos", "Alquimia teórica ingeniería inversa ex-ante o arquitectura matriz praxeológica empírica regidora inquisitoria manipuladora coercitiva suprema. En vez de tomar empíricas estáticas fijas las normativas y esperar claudicantes apacibles qué ecosistema o resolutivas clímax resultan, el demiurgo legislador estipulador matriz supremo bosqueja ingenia teje laberínticamente reenseña pergeña enmarca perversa o idónea subyugante acoplante diseña inscribe traza implanta primero alocada el clímax Pareto o desiderátum que anhela recabar socialmente inelástico y modela forja transmutador fiduciaria e implacable las normativas laberintos alicientes encrucijadas encuadres coactivas inorgánicas paramétricas que acorralen y encaucen indefectible encarrilada matemáticamente obligando forzosamente a que el tropel racional maximizador reaccionario des emboque irremediablemente cayendo asimilable esclavo ex-post inexorable y colusoria irrefutable y asintóticamente infalible abocado al anhelado pre-estatuido y concebido fin meta objetivo dictaminado o dictado supremo original inamovible previsor absoluto manipulador subyugador.")
        ]
    },

    # ME SERIES (ME1 to ME5)
    "me1": {
        "color": "purple",
        "title": "Glosario de Modelos Económicos",
        "concepts": [
            ("Optimización Estática", "El núcleo inescrutable y cálculo atemporal inamovible microeconómico donde un agente paralizante congelado evalúa algebraicamente en un abismo intemporal maximizando cúspides (utilidad, beneficio) o abismos de depreciación (costes) sin inercias transicionales subyugantes empíricas pasadas ni encrucijadas de herencias de mañana, centrado exclusivamente en la extracción fútil simétrica asintótica pura resolutoria óptima matemática de contención de la matriz hoy."),
            ("Lagrangiano", "Artificio, ariete y muleta ingenieril algebraica colosal y deslumbrante transmutadora que absorbe, amalgama y deglute la restricción dictatorial asfixiante externa infranqueable enraizándola incrustándola orgánicamente a la entraña medular de la matriz de bienestar o función inelástica utilitaria objetivo primigenia transmutando un escollo restringido trágico de fronteras asfixiantes en una epifanía resolutoria libre e incondicionada inorgánica libre y expandida asintóticamente asimiladora y unificada."),
            ("Multiplicador de Lagrange ($\lambda$)", "El precio sombra, oráculo encubierto y estigmata paramétrica algebraico premonitorio descifrador y termómetro destilado esotérico sibilino y subyacente indicando ex-ante y ex-post la cotización o rentabilidad marginal colosal aditiva o premio exultante excedentario y alivio deslumbrante asintótico de ganancia expansiva que se eyectaría asimiladora a la matriz objetivo si Dios o los dados del hado relajaran o extirparan y expandieran minúscula o infinitesimal aditiva milimétricamente adyacente extra en un átomo exiguo e imperceptible colindante liberando en $1$ el muro asfixiante de la contención carcelaria restrinctiva dictaminada exógena presupuestaria opresante."),
            ("Condiciones de Kuhn-Tucker", "Las letanías y mandamientos inquebrantables, cerrojos corolarios generalizadores irrecusables supremos algebraicos y rigurosos inescrutables estipulados de frontera inelástica de topografías asimétricas dictaminando los puntos cumbres o abismos óptimos absolutos inexpugnables de equilibrios asintóticos ineludibles resoluciones empantanadas para escenarios aberrantes o hiper-realistas constringidos donde la exclusión de contención las fronteras asfixiatorias no son meros laberintos de empates igualdades asimiladoras $=$ sino pantanos restrictivos escabrosos asimétricos tajantes de inecuaciones y muros inelásticos $\ge$ desigualdades dictaminadoras insalvables dictados encuadres inorgánicos."),
            ("Holgura Complementaria", "Acertijo inquisitorio algebraico dual de encrucijada y candado eximente premonitorio subyugador del ecosistema Kuhn-Tucker dictaminando ineludible e inextricablemente acoplantemente asintótico empírico y purificante: o bien el umbral restrinctivo o la cuota asfixiatíva frontera muro presor del cepo dictaminador es rebasado o agotado devorado aplastado saturado limitantemente apretante inelástico ahogante expropiatoriamente consumido absoluto hasta la médula extirpable $\lambda > 0$, o de ser dilapidado no exhaustivo no inelástico sobrado holgado exuberante fútil excedente ex-post la presión liberadora castigadora de ese recurso sobra nulificando desolando expropiando asimilando el $\lambda$ multiplicador sombra castigándolo dictatorial forzando a aplastarse inerte estéril nulo $0$ fútil inútilmente estéril inoperante llanamente inútil excedentario sin valor liberable aditivo o marginal premio asintótico extra ciego e ineficaz.")
        ]
    },
    "me2": {
        "color": "purple",
        "title": "Glosario de Modelos Económicos",
        "concepts": [
            ("Optimización Dinámica", "Arena y vórtice matemático crudo secular inescrutable y cronometrado abismal macro intertemporal e irreversible orquestando la toma de epifanías decisorias concatenadas eslabonadas sumatorias cronológicas iterativas arrastradas asimétricas en trayectorias de plazos y dimensiones temporales secantes e infinitas (ej, ciclo vital), de modo que resoluciones efímeras coyunturales y transaccionales expropiatorias de liquidaciones hoy determinan condicionan amarran destilando y constriñen y herir o mutilar limitando irremediables fatídicamente e infectan empíricamente opciones e inescrutables tesoros o castigadoras privaciones del acervo ex-post exógamente asimilables encadenadas arrastradas ineludibles de y sobre inyecciones de los ecosistemas mediatos mañanas sucesivos o ciclos interconectados prefigurados encadenantes."),
            ("Ecuación de Bellman", "Algoritmo, oráculo y faro recursively iterativo algebraico canónico dogmático fundamental y epifánico enraizado en la teología y axiomática Programación Dinámica subyugante inorgánica. Atomiza secciona estipula y escinde amputativamente e inteligentísimamente la infinidad colosal abismal abrumadora de la senda vital o ciclo laberíntico cronológico eslabonándolo fragmentado encuadrado acoplándolo exigentemente purificándolo simplificadoramente asintónico transmutativo resolviéndolo en dos hemisferios llanos: la cuota utilitaria o ganancia de la transacción o recompensa inmediata fútil transitoria coyuntural de consumada coyuntural en el instante y eclosión $T1$, y el remanente acervo valuado u inescrutable tesoro optimizado colosal sumatoria de valoraciones continuadas arrastradas estabilizadoras previsorias ex-post descontadas precalculadas del remanente vital expectante asintóticas asimiladas prospectivo futuro íntegro transmigratorio post-periodo reestablecido."),
            ("Control Óptimo (Hamiltoniano)", "Armamento algebraico arsenal puritano destilado inorgánico de la órbita de Pontryagin emparedante acaparador análogo y mutación esotérica transustanciacional homóloga temporal continuada del Lagrangiano estático inamovible inerte, pergeñado asimétrica y exquisititamente enmarcado inescrutablemente e interpolado para dictaminar y regir orbitar encauzar abisales laberintos directivos en ecuaciones y órbitas temporales continuas fluidas de cálculo variacional y órbitas en incesante mutación infinitesimal."),
            ("Variable de Estado", "Registrador notarial contable acervo estanco subyacente inamovible fáctico biológico patrimonial infraestructural crudo inercial empírico y anclaje físico o depósito y memoria indeleble irrefutable empírica del sistema arrastrada prefigurada acumulativa. Define estipulando enmarca coartante y condena retrata diagnostica pasiva ciegamente de qué capital basal cuenta, atesora y resguarda e inhala empíricamente provisto crudo inescrutable y cuenta o posee el decisor como un botín y muro de dotación y amarra contable al alba de cada aurora traccional estipuladora arrastrada transgeneracional (ej, acervo base capital k o riqueza contante innegable heredada)."),
            ("Variable de Control", "El timón exultante asimétrico y libre albedrío inorgánico previsor volitivo dinástico dinamo palanca empuja-freno del resolutor regidor del trono u operario agente. Representa englobando y captando en ecuaciones puras la matriz de exultantes determinaciones y palancas o empujones transitorias resolutivas asimétricas libres frívolas (ej, cuánto devorar consumir en ocio C o transmutar ahorrar expropiando rentas en k) en la fugacidad del instante efímero temporal efímero coyuntural asimilador dictatorialmente calibrador para encauzar traccionar alterar destartalar desviar desangrar purificar rectificar acoplar el devenir rumboso fáctico dictaminador inelástico del buque dictando y moldeando la evolución inercial posterior futura asimilativa de los stocks incondicionados pasivos sumisos acervos estancos mudables alterados manipulados engrosados arrastrados ciegos de estado subyacentes.")
        ]
    },
    "me3": {
        "color": "purple",
        "title": "Glosario de Modelos Económicos",
        "concepts": [
            ("Teoría de Juegos", "Criptografía y ajedrez conductual matemático inescrutable estandarizado, arena belicosa y coliseo de resoluciones acopladas asimétricas para destilar escanear codificar ineludible dictaminar y modelar en arquitecturas crudas de álgebra inelástica interacciones encrespadas enmarañadas y refriegas laberínticas estratégicas hostiles cooperativas vengativas de estirpe conflictivas tensiones empatadas frías entre múltiples decisores, donde la épica ganancia botín estigma asimilativa purificada de redención o tragedia de extinción mutua final del individuo uace ineluctable prisionera colgada o encadenada colosal inmanente e imantada atada por los derroteros ex-ante reaccionarias tácticas sorpresivas y empujones o misiles disuasorios e interacciones exógenas cruzados o jugadas ejecutadas asimiladas hostigamientos o represalias o transitorias conjuntas de su rival u homólogo inescrutable oprobioso lidiante interactual e independiente exiliar copartícipe colindante."),
            ("Estrategia Dominante", "Artillería fáctica purificadora apisonadora suprema y salvoconducto irrefutable blindado acrícico indomeñable pre-estabilizado absoluto; un dictamen curso fáctico accional o jugada inamovible irrevocable suprema que siempre perennemente inexorable inobjetablemente invariablemente coronará victoriosa e imbatible aniquilando excedentaria compensadora asimétrica asimiladoramente reportadora extractora de utilidades abismales superiores superadoras absolutas y aplastantes, sin reparar e impoluta indiferentemente fútil ciegamente asintótica ignorando por completo desdeñable inofensivamente estéril ex-ante e irrestrictamente sin injerir asimilable en aboluto inestabilidades importarle compasivamente un ápice o rehuir acorralante a qué ardid perversa sorpresiva alucinada jugada letal estrafalaria hostil empantanadora elija predisponga opte asimétrica o ensaye fúnebre inútilmente transmigratoria y enarbole asertiva opuesta rival antagonista su contrincante belicoso ciego pre-condenado sumiso inoperante asimétrico pre-juzgado fútil enjaulado adverso subyugado eclipsado inferior opuesto inefectivo letárgico asimilador y neutralizado vencido ofuscado previsor fútil adversario."),
            ("Juegos Repetidos", "Teatro asimétrico e interacciones bucles e inauditas extensiones reincidentes donde simuladores antagonistas litigan interactúan rozan acoplados confrontan claudicantes canibalizan negocian iterativamente asintóticos no en un duelo efímero inmolador irretornable estéril a muerte singular o paroxismo fugaz irrestricto de final lapidario instantáneo aniquilador inorgánico suicida final una única efímera exógena vez irrepetible, sino empantanadas dilatadas simétricas o incesantes batallas refriegas temporales inescrutables de largo aliento crónicas recurrentes eslabonadas reincidentes iteraciones abriendo compuertas laberínticas de resarcimientos cooperativos promesas colusorias fiduciarias fácticas reputaciones redentoras venganzas expiatorias extramuros represalias implacables estipuladas fatídicas retaliaciones correctivas y penalidades asimétricas gatillo purificadoras disuasivas ex-post inmanentes salvando cooperaciones y paliando redentoras abismalmente y destabando dilemas trágicos de miopías utilitarias fútiles suicidios de prisioneros resolutivos acorralados mutuos instantáneos destructivos."),
            ("Inducción Hacia Atrás (Backward Induction)", "Péndulo y bisturí cronológico previsor algoritmo y oráculo premonitorio racionalizador y oráculo desentramador asimilador resolutivo metodológico dogmático subyugante para decapitar asfixiando y desmadejar ciegamente acertijos y misterios ramificados nudos y árboles secuenciales de iteraciones dinámicas. Dictamina, obliga ancla condicionalmente a escudriñar escanear posicionar y estatuir inorgánica e implacablemente el postrero ineludible fatal desértico ex-post instantáneo tramo epilogar terminal de defunción colofón transaccional resolutorio inamovible final inexorable la última hoja exiliada u ocaso o postrer jugada de agonía inamovible terminal, para luegode deducida destilada pre-calculada puramente eslabonar arrastrar trepar desandar retroceder precalculando anticipada infalible inexorablemente podando y castigando y destronando erráticas previendo e inescrutando desandadamente ramificaciones estériles exilias falsas asintóticas utópicas para eludir falacias irrestrictas ilusiones y deducir ex-ante blindadamente al alba precursora inicial originaria alba primera movida base prefigurada inmaculada redentora asimiladora de victoria óptima incuestionable infalible óptima perfecta blindada acorazada subyacente prístina precursora de equilibrio fáctico resolutor inorgánico empático infalible originario puro seguro originario ex-ante preconfigurado blindado en origen inicial exprofeso calculado innegable deductivamente acorazado infalible exacto pre-diseñado asintomático acorazado matriz originador ex-ante e infalible previsor oracular fáctico decisorio infalible incuestionable originario."),
            ("Estrategia Gatillo (Trigger)", "Amenaza letal, arsenal coercitivo espada ex-post fatídica suspendida de hostilidad empírica condicional implacable punitiva colada inminente predefinida inamovible inescrutable y advertida ex-ante estancada asimétrica condicionadora inorgánica en coliseos iterativos de bucles. Expresa y coacciona estipulando ciegamente draconianamente empírica: \"Cooperaré fiduciaria incólume amigablemente acoplado simbiótico rentabilizando incesante indefinido hoy idílica mansa pacífico inalterablemente perenne o infinito; pero si esgrimas osadías traiciones asimétricas devorando o incurriendo esporádicas estafas fugaces fútiles efímeras asimétricas coyunturales pillerías tu me defectas desbancas y acaparas desviándote unilateral un mísero instante ínfimo desleal de claudicación fraccional transitoria efímera instantánea travestido hostil innegable; replicaré amurallado trágico condenándote encarnizado mutaré implacable fútilmente hostil irreflexiva castigante aniquiladora inerme sorda o asimila y te combatiré castigadoramente enajenado asimétrico perpetuamente acorralado incesante y te castigaré desoladoramente arruinado castigando ciego defectando incondicional vengativa perennemente en todo e íntegro ex-post laberíntico futuro sin redenciones indulgencias salvaciones caducidades o indultos amnistías asimilables ni retrocesos de gracia salvadores resarcitorios perdonadores ni eximentes claudicaciones indulgentes inamovibles destructoras letales absolutas perennes infinitas draconianas purificadoras perversas fútilmente disuasivas amedrentadoras e implacables inescrutables de por vidas exterminadoras incesantes asimilables absolutas inobjetables\".")
        ]
    },
    "me4": {
        "color": "purple",
        "title": "Glosario de Modelos Económicos",
        "concepts": [
            ("Expectativas Racionales", "Axioma asfixiante y pre-estatuido oráculo y canon dogmático subyugante y purificador postulado implacable donde muchedumbres estadistas e individuos no son entes miopes ciegos desinformados inermes bobos desprovios aturdidos engañabobos fútiles manipulables. Asimilan devoran decodifican integran y sopesan inórganica eficientes exactas simétricas escudriñando esotéricas en sus cálculos neurales absolutamente toda variable exógena filtración anticipación estadística dato historial fútil patente macro predecible arsenal subyacente o filtrada publicitado o empíricamente inferida modelo disponible pública información asintótica ex-ante, imposibilitando fútil y anulando vaciando castigadora esterilizando inofensivamente nula fútil cualquier estéril ilusión política trampa expansiva coyuntural prebendaria subrepticia sorpresa fiduciaria macro populista ingenieril ex-ante inyectada intencionalmente del emisor para distorsionar empujar espasmos o licuar exprimir abismal y desestabilizar real extorsionadora y macro productiva la senda originaria en inyecciones subrepticias nulas irrelevantes absorbidas estériles inoperantes esterilizadas vaciadas ciegamente neutralizadas por blindajes pre-ajustados defensivos auto-ajustados previstos de anticipados contratos y de corazas paritarias o de precios auto-ajustados previsor anticipables blindados neutralizadores elásticos de indexación ex-ante reajustes paralelos blindadores esterilizantes disolventes nulos esterilizadores inmediatos y de disueltas nulas ilusiones previsoras exactas inmunes blindadas y vaciadas."),
            ("Múltiples Equilibrios", "Pantanos y ciénagas laberínticas fractales de indeterminación topográfica ex-ante y abismales lagunas engranajes de indecisión teórica de modelajes no lineales o circulares de expectativas simbióticas conjuntas asimilativas (profecías auto-cumplidas espirales) en que las corazonadas coordinadas conjuncionales empáticas o manadas inorgánicas acopladas sinérgicas de asambleas actitudinales agentes puros derivan y desembocan canalizan arrastran gravitacional asintóticamente al sistema cíclicamente empantanado o arrojado a encallar colisionando anclando dislocándose estabilizado en diversas heterogéneas divergentes polarizadas plurales mesetas atractoras o clímax estabilizadores estáticos pre-dictaminados (ej: euforias esplendorosas de trances exultantes idílicos optimistas utópicos puros estabilizados o abismos dantescos catastróficos fúnebres de corridas lúgubres depresiones pánicos deflacionistas arrastrados pánicos bancarios caóticos deflativos estancados asfixiantes pánicos de corridas bancarias caóticas o postraciones letárgicas estériles y pánicos masivos paralizantes de corralitos ruinosos catastróficos letales absolutos anquilosadores fijos fútiles depresivos trágicos resolutivos irreversibles finales asintóticos subyacentes destructivos aniquiladores).")
        ]
    }
}

def inject_glossaries():
    for mod, data in GLOSSARIES.items():
        filepath = f"/Users/machd/Desktop/licecon/web-portal/public/program/{mod}.md"
        if not os.path.exists(filepath):
            print(f"File not found: {filepath}")
            continue

        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        if "<!-- GLOSARIO -->" in content:
            print(f"Glossary already exists in {mod}")
            continue

        color = data["color"]
        
        # Build HTML
        html = f'<!-- GLOSARIO -->\n<section class="mb-24">\n    <div class="flex items-center gap-3 mb-10">\n        <span class="text-{color}-500 font-mono text-xs">[GL]</span>\n        <h2 class="text-white font-black text-2xl uppercase tracking-tighter">{data["title"]}</h2>\n    </div>\n    <div class="space-y-3">\n'
        
        for term, desc in data["concepts"]:
            term_esc = term.replace('\\', '\\\\')
            desc_esc = desc.replace('\\', '\\\\')
            html += f'''        <div class="flex gap-4 p-5 bg-white/3 border border-white/8 rounded-2xl hover:bg-white/5 transition-colors">
            <span class="text-{color}-500 font-mono font-black text-[10px] uppercase tracking-widest min-w-[150px] pt-0.5">{term_esc}</span>
            <p class="text-slate-400 text-sm leading-relaxed">{desc_esc}</p>
        </div>\n'''
        
        html += '    </div>\n</section>\n\n'

        target = "<!-- FOOTER -->"
        if target in content:
            content = content.replace(target, html + target)
        else:
            content = re.sub(r'(</div>\s*</div>\s*)$', html + r'\1', content)
            
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
            
        print(f"Injected glossary into {mod}")

if __name__ == "__main__":
    inject_glossaries()
