import os
import re

GLOSSARIES = {
    # MAC SERIES (6 to 10)
    "mac6": {
        "color": "fuchsia",
        "title": "Glosario de Macroeconomía",
        "concepts": [
            ("Economía Abierta", "Sistema interconectado sin autarquías, interactuando irrestrictamente y fluidamente con el resto de geografías mundiales mediante intensos transfronterizos tráficos de exportaciones, importaciones e incesantes radicaciones e inyecciones o fugas de portafolios de flujos internacionales de capitales."),
            ("Exportaciones Netas (NX)", "El saldo arrojado riguroso por la Balanza Comercial de una nación (Exportaciones restadas de Importaciones). Determina si un país gasta o financia globalmente o acumula rentas superavitarias."),
            ("Salida Neta de Capitales (SNC)", "Aquisiciones e inyecciones de activos físicos o papel extranjero domiciliado en exterior ejecutada y abonada por residentes nacionales neteada contra y menos las adquisiciones de activos domésticos detraída a foráneos."),
            ("Identidad S - I = NX", "Igualación macro contable universal de economías abiertas vinculando indisolublemente y hermanadamente los ahorros nacionales excedentes canalizados al exterior frente al saldo o cuenta comercial gemela paralela idéntica."),
            ("Tipo de Cambio Nominal", "Precio relativo nominal, fraccionario o multiplicado, estableciendo y acordando empíricamente la pura conversión fiduciaria y proporción neta permutable o ratio exacto de transacciones entre dos divisas físicas de dos naciones distintas."),
            ("Tipo de Cambio Real", "Tasa y radar fidedigno del valor y competitividad transfronteriza subyugante, expresando rigurosamente a qué ratio los bienes físicos palpables y canastas mercantiles originarias equivalentes de un país se trocan paritariamente frente a idéntica foránea."),
            ("Paridad de Poder Adquisitivo (PPP)", "Teoría tendencial fundamental indicando que, expurgadas las trabas formales logísticas, una unidad monetaria unívoca idéntica detentará universal y mundialmente el mismo potencial y vigor poder adquisitivo homologado a la red de igualaciones de arbitraje de la ley de un solo precio total."),
            ("Ventaja Comercial Absoluta", "Potencialidad logística u operaria de una entidad de fabricar genérica unídireccionalmente un bien final invirtiendo y quemando intrínsecamente inferiores sumas de factores horas o dotaciones que rivales extranjeros geográficos."),
            ("Déficit Gemelos", "Incidencia fatal asimétrica y empírica comprobada donde irresponsables dilapidaciones y socavones de cuentas tesoreras Estatales (Déficit presupuestario originario) traccionan irremediablemente al país a devorar forzosamente financiaciones capitales externas hundiendo (Déficits de Cuenta Corriente asociados paralelos)."),
            ("Apreciación / Depreciación", "Alzas o encarecimientos unitarios del valor convalidado cambiario o recortes relativos y depreciativos de una moneda frente a sus pares flotantes extranjeras puras en los regímenes desregulados y transables y cruzados internacionales de forex mundiales continuos.")
        ]
    },
    "mac7": {
        "color": "fuchsia",
        "title": "Glosario de Macroeconomía",
        "concepts": [
            ("Tasa Natural de Paro", "Umbral sistémico crónico promedio empírico persistente normativo fluctuante subyacente de la desocupación. Rango gravitacional e inercial donde colapsa o retorna predeterminadamente secular el desempleo en largos horizontes, eludiendo transitoriedades ilusorias efímeras cíclicas pasajeras o coyunturas sobrecalentadas."),
            ("Paro Friccional", "Desocupación efímera o inercial coyuntural innegable transicional y temporal o inevitable natural intrínseco resultante e injertada en los retrasos y lentitudes y asimetrías de tiempo entre dimisiones y búsqueda acopladora relocalizadora y emparejamientos en rotaciones demográficas puras entre ofertantes aptos laborales y nuevas eclosiones corporativas de rubros dinámicos nacientes incipientes productivos incesantes recambios."),
            ("Paro Estructural", "Rigidez o cristalización sistémica irreductible del desempleo crónico cuando coaccionadas imposiciones de legisladores inflexibles distópicos fijan los tabuladores de remuneraciones de salarios base coactivos artificiales autoritarios y prebendarios draconianos sustancialmente y dictatorialmente elevadísimos inalcanzables inaccesible excluyentemente colosales superadores en exorbitancias del mercado del equilibrio asintótico del vaciado pleno salarial productivo demandante excluyendo en el ostracismo excluyente letal legal general forzosamente a inoperantes o masas obreras primarias originarias sin formación técnica demandable insertable rentabilizable."),
            ("Salarios de Eficiencia", "Racionalidad e ingenieril e intrínseca e imperativa de los capitalistas optando libre, unilateral y deliberadamente de abonar y encumbrar de propia voluntad sueldos exuberantes sobrepromedios al margen basal para forjar, incentivar e inmunizar y atar lealtades operarias en salud laboral y repeler sangrías de rotaciones inestabilidades y maximizar rendimientos leales esforzados óptimos atrincherados funcionales en sus obreros dependientes fidelizados optimizados selectos insobornables alineando estímulos puros preventivos productivistas directos disuasorios motivacionales."),
            ("Rigidez Salarial", "Inflexibilidades perversas nominales paralizantes, resistencias inamovibles gremiales sindicalizadas atávicas o contratos estáticos fosilizados impidiendo reajustes deflacionarios lógicos correctivos ante mermas productivas recesivas, originando desempleos colosales y marginando y cesando o expidiendo a operarios por asfixia en la carga insostenida inviable estructural invendible incosteable imposibilitando reabastecidas absorciones flexibles reactivadoras salivadoras asimétricas de reactivaciones elásticas sanadoras orgánicas reequilibradoras puras."),
            ("Curva de Phillips de Corto Plazo", "Un trade-off temporal empírico fraccionado o encrucijada y disyuntiva macro transitoria efímera perversa donde políticas inyectoras o calentamientos recalentadores espasmódicos expansionarios consiguen engañosamente o fiduciariamente disminuir los desocupados fugazmente, asumiendo o cobrando inflaciones encarecedoras impositivas y destructivas asimétricas generalizadas en contraprestación compensatoria letal engañosa distorsionadora inestable fútil aparente temporal."),
            ("Seguro de Desempleo", "Asistencia amortiguadora provista centralmente por colectas fiscales a desempleados, que si bien suaviza letalidades de subsistencia temporal humanas, empíricamente engendra y magnifica el paro friccional exacerbándolo en morosidades selectivas o holgazanerías transicionales mermando desesperaciones urgentes de inmediata abdicadora desesperada reinsercional en salarios base disminuidos forzosos de reencauzamientos subóptimos."),
            ("Leyes de Salario Mínimo", "Intervencionismo puro en techos artificiales garantizados en imposiciones punitivas para el empleo y contrataciones formales basales exógenas en legalidades. Causa y acentúa estructural y endémicamente de forzada exclusión de desempleo excluyente absoluto cruel asimétrico para estratos jóvenes inexpertos crónicos estigmatizantes formales si la cuantía supera su valor productivo real aportable originario productivista medible utilitario marginal compensador directo subyacente."),
            ("Población Inactiva", "Demografías civiles excluidas o auto-abdicadas disueltas o sin incursiones ni en el renglón operario laboral ocupado actual ni en el padrón desesperante y contable activo de peticionantes insistentes rastreadores en búsqueda de empleos formales en encuestas (ej: estudiantes crónicos, amas, pensionados o dimitentes rendidos inactivos exiliados frustrados desistidos)."),
            ("Demanda Insatisfecha Oculta", "Necesidades corporativas latentes reprimidas paralizadas o vacantes sin ofertante de postulantes o que corporaciones renuncian o retiran forzosamente sus aperturas en plazas asfixiantes o paralizadas ante cargas colosales asfixiatorias laborales o arriesgamientos asimétricos despido-penas judiciales o inusitadas disfuncionales imposiciones formales rigorisadas exentas paralizadas inviables en encarecimientos directos inoportunos irracionales perversos castigadores preventivos de inacción conservadora defensiva paralizadora del empresariado precavido.")
        ]
    },
    "mac8": {
        "color": "fuchsia",
        "title": "Glosario de Macroeconomía",
        "concepts": [
            ("Estado Estacionario (Steady State)", "Clímax analítico y punto de fuga, confluencia e igualación convergente matemático y gravitacional del modelo Solow donde inyecciones e incrementos o ahorros sumados netos formativos invirtientes acopiadores de nuevos capitales $I$ empatan asombrosamente y compensan matemática estricta a depreciaciones disolventes desgarradoras crónicas fatales desgaste inercial de amortización obsolescente $dK$ licuando y estacionando y estatizando inmovilizando los crecimientos expansivos netos estáticos asintóticos estabilizados nulos incrementales cero per-cápita equilibrados formales constantes fijados inamovibles definitivos."),
            ("Acumulación de Capital", "El torrente ahorrativo exento consumos diferidos del ingreso que la economía civil destina inyecta e hunda pre-invierte preconstituyente y consolide y erige fraguando e inmoviliza físicamente transustanciada a maquinaria tecno-instrumental plantas tractores insumos herramientas engrosando y dilatando los radios intensivos apalancadores amplificadores o arsenales tecnológicos industriales a disposición multiplicadora potenciando labor humana ruda intensificada exógena per cápita predeterminante enriquecedora base central de producto incrementando."),
            ("Regla de Oro (Golden Rule)", "La condición superlativa óptima medular canónica del estado estacionario y vector de tasa ahorrativa cumbre calibradísima suprema ex-ante selectivamente planeable utópica macro, donde el consumo per-cápita maximizado y engalanador se estabiliza perpetuable transgeneracional estáticamente imperecederamente sin deprimir capital a futuras progenies; dictaminada algebraicamente cuando producto marginal de capital detiene y calca exacto a tasa depreciatoria $PMK = \delta$."),
            ("Tasa de Ahorro ($s$)", "Proporcional fraccional base contable empírica sociológica exógena que estipula y comanda el total asimétrico drenado porcentual de toda renta nacional que es abstraída inexorable exógenamente del goce y frivolidad e ingesta presente consumista efímero fútil disipadora aletargante priorizando y derivándose excedentemente estricto íntegra productivistamente puritana austera para erigir consolidar inversiones originarias duraderas estancar multiplicadora."),
            ("Depreciación ($\delta$)", "Erosionamiento pernicioso fatídico y licuatoria intrínseca destructibilidad material fatídica implacable crónica letal atávica obsolesciendo friccional maderera del parque fabril total físico oxidando devaluador y corroyendo acervos originarios constantes preconstituidos asimétrica e inflexiblemente como cuota fraccional temporal letal inevitable que socava inexorable y drena capitales en la temporalidad mermando los stock operativos base reduciéndolos."),
            ("Crecimiento Poblacional ($n$)", "Variable diluyente y diseminadora multiplicada estricta demográfica fraccionadora en la ecuación soloviana que esparce constrictiva la provisión acumulativa fija general engrosada de capitales entre crecientes divisorios e insertos obreros muchedumbres originarias diluyendo o atomizando y raleando asfixiante el radio tecno-intensivo unitario per cápita licuando individualidades mermando a los stock instrumentales fraccionados y ralentizando consecuencialmente producto rentístico unitario diluible."),
            ("Dinámica de Transición", "Movilidad vectorial traccional direccional originaria de la lejanía estructural del parque capital al estado inercial estacionario convergente; a inferior e irrisorio acervo de partida arranca subyacente vertiginosa e intensa expansión rauda raudísima acelerativa o convergente alcanzadora exponencial inicial de crecimiento e irá languideciendo apagándose desacelerándose mermándose decreciente subyacentemente al enrrocar y asintotar frenándose atenuantemente hacia estabilidades fijas absolutas limitadas inamovibles letárgicas finales asintóticas culminantes estacionarias del techo."),
            ("Eficiencia del Trabajo ($E$)", "Un calibrador algebraico indexador y multiplicador subyacente puramente tecnológico e intelectual no observable fisiológico. Acentúa y sobrecalifica e imbuye a los perfiles humanos brutos de saberes destrezas innovaciones sinuosas incrementando endiabladamente productividades aparentes o virtuales operando rindiendo como si formaciones obreros ficticios clones incesantes engrosaran sumatorias equivalentes virtuales colosales operarios efectivos agigantados potenciados ilusionando y multiplicando y propulsando productos por tecnificación adosada añadida intangible inyectada."),
            ("Progreso Tecnológico ($g$)", "El único y divino motor perpetuo, dinamo sagrado e irreemplazable de la ortodoxia Solow resolviendo enigmas para eludir colapsos de parálisis final melancólica estacionaria en estándares y retornos fijos perpetuables; inyectando externalidad expansiva y redentoras infinitas crecientes expansivas colosales rentas de crecimiento per cápita secular eterno continuo salvador sustentable asimétrico sin frenos ni rendimientos decrecientes inamovibles insuperables estancadores perpetuos constantes permanentes definitivos e inmodificables fijos eternos insalvables limitantes de acumulación cruda exclusiva y material neta simple solitaria y vacía o exclusiva.")
        ]
    },
    "mac9": {
        "color": "fuchsia",
        "title": "Glosario de Macroeconomía",
        "concepts": [
            ("Crecimiento Endógeno", "Cisma y rebeldía herética a Solow. Modelajes de vanguardia donde la propulsión milagrosa e infinitas escaladas tecnológicas vanguardistas innovadoras no llueven dadas maná exógenamente providenciales caídas mágicas del cielo ajenas impredecibles inalterables aleatorias subyacentes mágicas, sino brotan intrínseca endógenamente forzadas y destiladas de asimilaciones o eclosiones e inversiones patentes en cerebros de educación e i+D exclamando por retornos crecientes constantes."),
            ("Externalidad de Conocimiento", "Desborde derramador benefactorio y fertilizante intrínseco indirecto inintencionado providencial pero exultante de la educación intelectiva, invenciones y matrices capitalistas innovadoras patentes donde hallazgos, luces, revelaciones descubrimientos se escapan asimétricamente plagiadas imitadas esparciéndose por el tejido social asimiladora impregnándolo y propulsando generalidades y sinergias catapultadoras agigantadoras y empoderadoras colosales para acervos agenos macro sin cobro directo monopolizador apropiador completo absoluto exclusivo de regalías de su creador pionero base de origen descubridor primerizo."),
            ("Rendimientos Crecientes", "Abandono al pesimismo del decrecimiento clásico marginado, admitiendo que si saberes intelectivos, infraestructuras y externalidades macroestructurales convergen en densidades productivistas masivas o aglomeraciones, cada inyección macro marginal originaria retribuirá expansivamente superadoramente y eclosionará rentabilidades superlativas y excedentes abrumadores o compensantes propulsando despegues económicos vertiginosamente inagotables sin atascos letárgicos estacionarios convergentes atrayentes asintóticos."),
            ("Protección Intelectual", "Salvaguardas estatales restrictivas institucionales como patentes, escudos o registros marcarios derechosos imprescindibles ex ante exigiéndose para erigirse monopólico transitorio asimilador de su lucro originante asegurándole estímulos y resarcimientos exorbitantes e inyectores motivantes iniciales y compensaciones y pre-empeños de genios sacrificados asimétricos inversores corporativos farmacéuticos laboratorios vanguardistas pioneras disrumptivas investigatrices de capitalización previa originaria cruda pesada adelantada irrembolsable hundida azarosa incierta inicial abismal hundida ciegamente experimental puritana arduamente abismal y aventurera investigativo incipiente arriesgada incierta subyacente fútil riesgosa investigativa."),
            ("Capital Humano", "Cuantificación, estandarización y capitalización agregada e invisible invaluable inamovible transgeneracional abstracta corpórea intrínseca biológica inalienable inherente de habilidades, maestrías, sanidades, nutriciones, adiestramientos gremiales destrezas instruccionales inyectadas y asimiladas encarnadas forjadas y educadas infundidas endógenamente fraguadas adquiridas formativamente por la plebe operaria enriqueciendo exorbitante cualitativamente mentes transformándolas a acervos colosales activos instrumentales abstractos rendidores perennes multiplicadores eclosiones cognitivas abstractas productivas y redituables valiosísimamente originarias insustituibles basales inalienables intrínsecas vitales de la clase productiva cívica obrera laboriosa ciudadana formativamente ilustrada selecta entrenada perita forjada ilustrada capacitada."),
            ("Inversión en I+D", "Inyección y derramamiento, desvíos y quema ex profeso asimétrica agresiva corporativa de utilidades en departamentos insondables ciegos científicos o experimentales lúdico arriesgados azarosos inciertos inciertos en persecuciones originarias tecno-revolucionarias para generar alquimias productivas fórmulas o arquitecturas eficientísticas disruptivas superadoras que destilen innovaciones perennes de quiebres destructivos creadores schumpeterianas patentes monopólicas transitorias hegemónicas colosales hiperrentables ex-post de éxito."),
            ("Convergencia Condicional", "Predicción empírica estadística de naciones donde países menesterosos paupérrimos o subdesarrollados carentes o empobrecidos originarios acelerarán o crecerán abrumadoramente agigantadamente veloces fugaces de partida a tasas estratosféricas transicionales chinas de recuperación hasta alcanzar convergir igualaciones a elites y potencias industrialistas preestablecidos y estáticos occidentales ricas desarrolladas sólo y excluyentementes si, y condicionadamente si, replican e incurren gemelamente los ecosistemas institucionales aperturas capitalizaciones ahorrativas o demografías análogas estructuradas formativas homologadas calcos asimilables estabilidades predecibles y civilizatorios ecosistemas seguros estables e idóneos propicios simétricos resguardadores institucionales subyacentes protectores civilizadores formativos idóneos resguardativos."),
            ("Hipótesis del Alcance (Catch-up)", "Ventaja coyuntural parasitaria o emuladora inercial providencial o imitativa transicional prestada o adquirida gratuita veloz tecnológica asimétrica para los naciones regagadas periféricas de copiar incólumamente saltando estadios de desarrollos caligiros copiando patentes o implementando infraestructuras foráneas prestabilizadas exógenamente desarrolladas extranjeras sin padecer, quemar recursos errados, desangrar experimentaciones incipientes infructuosas costosas pioneras asimiladoras y sinuosos padecimientos y tiempos generacionales seculares o errores históricos quemados originarios por originadores pioneros desarrolladores en la vanguardia pre-evolutiva occidental originarios sufridos ciegos."),
            ("Destrucción Creativa", "La lógica cíclica purificadora letal cismática shumpeteriana implacable y necesaria dolorosa reestructuradora exógena disruptiva implacable letal de eclosión innovadora salvaje desarticulando monopólos obsoletos barriendo y caducando y pulverizando tecnologías perdedoras marginando rubros rezagados arruinando inversiones anquilosadas estancadas extinguidas liquidando y exterminando e inmolando fósiles atávicos corporativos industriales forzando mudanzas e hibridaciones mutacionalismos y eclosiones pujantes revitalizadoras indomables dinamo perenne del libre albedrío inagotablemente incesante regenerativo motor del capitalismo vanguardista libre descentralizado.")
        ]
    },
    "mac10": {
        "color": "fuchsia",
        "title": "Glosario de Macroeconomía",
        "concepts": [
            ("Demanda Agregada (DA)", "La agregación aglutinadora y sumatoria contable asintótica inversa y de interrelación simbiótica colosal de las intenciones de demandas totales conjuntas globales ($Y = C + I + G + NX$) por toda mercancía o trabajo generadas exógenamente y planificada domésticamente a plenos en correlación declinante inexorable a oscilaciones deflativas y asimetrías de presiones a cada inestable rango e intervalo oscilatorio hipotético continuo nominal estriccional unitario encarecedor cambiante subyacente previsor general del índice unitario de precios macro general escalable P o nivel precios globales macro general nominal base asimilador encarecedor."),
            ("Oferta Agregada (OA)", "La cuantía o vector funcional matemático macro o techo pre-volitivo masivo que postula rígidamente e inercialmente cuántos acervos y volúmenes palpables físicos de manufacturamientos y acopios reales los capitalistas productores empresarios e industriales dictaminarán ofrecer e interponer mercadológicamente asimilablemente dependiendo y acoplado fuertemente subyacentemente al umbral estipulativo, estacional, rígidamente fijado o desbordado libre oscilatoriamente flexible escalable imperante en su rentabilización de precios fijados P cobrables del entorno circundante preestablecido macro o fijos en el horizonte nominal mediato observable nominal inmediato observable imperante."),
            ("Oferta Agregada a Corto Plazo", "Asunción o hipótesis y franja predeterminada temporal de inercia inamovible de rigidez pegajosa asimétrica estructural inelástica plana en escaladas (curva horizontal keynesiana post-fijadora) donde los capitalistas no recambiarán de inmediato tabulares ni nóminas tarifarias catálogas pegadas respondiendo expandiendo irrestrictamente acopios elásticas supliendo acaparadoramente choques en peticiones de sobrecalentamientos ciegos complacientes plénamente toda alza repentina irracional inyectada abrupta inorgánica irrestricta expansiva acomodando abastecimientos ciegamente expandidos acaparadoramente inyectivos transitorios a un nominal congelado fijado fútil plano inercial nominal y no ajustado nominal plano aparente constante nominal fijo coyuntural rígido subyacente temporal irreal transitorio o efímero ciego transitorio inestable en temporalidad."),
            ("Oferta Agregada a Largo Plazo", "Dictamen irrefutable de inelasticidad monetaria asimilado ortodoxo neoclásico postulado irrefutable vertical de inexorable asintota fija de dictadura absoluta e imperial física absoluta real. A horizontes alejados expansiones nominadas inician inyecciones nulas impotentes irreales inanes fútiles ilusorias; el parque o potencial producto total asintótico estacionado productivo o pleno $Y$ está estatuido forzosamente anclado clavado rígidamente inescrutable y exclusivamente a fundaciones materiales basales $K$ y $L$ productivos disponibles inamovibles estáticos crudos reales originarios plenos de frontera imposibles de inflar manipulando ilusionistamente y fútil inútilmente artificios imprimiendo liquidez nominativa o infladores fiduciarias artificiales inanes impotentes estériles vacíos expansivos transitorios coyunturales fútiles estériles irreales nulos transitorios fingidos irrelevantes ilusos."),
            ("Choques de Demanda", "Terremotos o sorpresas abruptas pánicos exógenos o alucinantes eclosiones de optimismo avasallante e intempestivos impredecibles impulsos exógenos expansivos en las ecuaciones $C$ o $I$ (ej. quiebras bancarias mermando e insolventando consumos o boom especulativo eclosionador animal spirits avasallantes optimistas) o políticas fiduciarias alocadas imprevisibles del BC o despilfarros tesoreros intempestivas inorgánicas dislocando empírica sorpresivamente al modelo DA inercialmente estáticos perturbándolos y transmutando trasladando en empujes expansivos contrayentes a la matriz plana desplazadora asintótica descolocándolos cíclicamente fuera dictatorialmente del cauce previsor oscilatorio estable basal inamovible."),
            ("Choques de Oferta", "Desastres fatídicos inauditos crudos catastróficos u holocaustos logísticos exógenos o paralizaciones mundiales drásticas petroleras sequías escaseces crónicas o destrucciones guerras agigantando exorbitante intempestivo sorpresivo letal impredecible el peaje productivo unitario originario de costos asfixiadores generalizando estrangulando asfixiantemente encarecedores marginales colosales (estanflación estigmatizante desarticulante destructiva) retorciendo e impactando asfixiantemente retrayendo destructivamente los techos escalafones oferentes paralizando retrayendo asfixiantemente abrumador e impactando e involucionando recesiones ineludibles destructivas inflacionadoras abrumadoras desoladoras contraccionistas al modelo estancando retrayéndolo irremediablemente desestructurales de manera asfixiante recesiva letal de costos destructora."),
            ("Estanflación (Stagflation)", "Paroxismo o aberración trágica paradójica endémica disfuncional para el trade-off empírico enmarañada inestable de curvas keynesianas puras donde eclosionan simbiótica simultánea e indomeñablemente y fatídicamente estancamientos productivistas retracciones operarias desoladoras, inauditas asfixiantes o languideces laborales desempleos crudos colosales conjuntas o amalgamadas inexplicada combinatoriamente simbióticas conjunciones asimétricas destructivas letales desastrosas colosales entrelazadas asimiladas funestas acopladas o confluenciadas fusionadas empíricamente e irresolubles con alzas devoradoras estratosféricas generalizadas inflacionarias y acelerada empobrececedoras letales espiralizadas acelerativas recesivas fatales agudas asoladoras incontroladas exarcerbadas galopantes crudas fútiles encarecedoras crónicas destructivas de asfixias letales de devaluaciones constantes encarecedoras persistiendo e inflando al unísono."),
            ("Políticas de Estabilización", "Ingenierías, intromisiones mitigadoras e inducciones contra-cíclicas exogenas reactivadoras y amortiguadoras estabilizantes de ministerios y centrales emisores previsoramente contrarrestando oscilaciones péndulas trágicas recesivas atenuando desplomes espasmódicos insólitos del PIB atemperando los cráteres abisales letales disipadores suavizantes contracíclicos resguardadores apaciguantes y domadores cíclicos de choques abismales deflacionistas en reactivaciones expansivas fiduciarias y mermando recalentamientos frenando atenuando y morigerando y aplacando eclosiones exuberantes espumosas encarecedoras inflacionistas recalentadas transicionalmente espasmódicas coyunturales extremas descontroladas de boom coyuntural."),
            ("Estabilidad Cíclica", "El fin perseguido de domesticación o de utópico dominio aplacador de la montaña rusa caótica empírica capitalista suavizando e injertando en sendero recto sin volatilidades traumáticas la senda de $Y$ evitando letalidades desempleos masivas por mermas en recesiones y espirales devoradores empobrecedores hiperinflaciones de devaluaciones continuas y recalentadas incesantes, promoviendo o inyectando o previsoramente contrayendo contracíclico calibrado en equilibrios fijos constantes en horizontes mediatos continuos estables inamovibles de prosperos horizontes transitorios estables seguros."),
            ("Efecto de Saldos Reales (Pigou)", "Mecanismo autosanador en crisis. Caídas generalísimas brutales drásticas deflacionarias liquidadoras en el marco $P$ paradójicamente engrosan e inyectan fortificando agigantando elástico exponencial fortalecido el escudo purificable y portafolio fiduciario liquidable de billeteras monetizadas o tesoros de efectivo deudores de ciudadanos atesoradores acaparadores foráneos $M/P$, desatando o infundiéndole sensaciones preceptoras de riqueza fiduciaria estimulante expandiéndolos euforicamente inyectándoles ánimos volitivos dispendiosos de incentivos reviviendo expansivamente estimuladores de consumos macro resucitadores correctivos de inmersiones reactivantes en espirales de consumo basal $C$ que reviven cíclicamente en alza o rescates a asintotas inerciales endógenamente.")
        ]
    },
    
    # MIC SERIES (micro1 to micro5)
    "mic1": {
        "color": "indigo",
        "title": "Glosario de Microeconomía",
        "concepts": [
            ("Escasez", "El axioma base. Disyuntiva y limitante o déficit originario perenne que acorrala irrestrictamente forzosamente las opulencias o inmensidades deseos insaciables inagotables del individuo constringiéndolos a chocarse ineludibles fatales inexorables barreras y cuotas presupuestarias linitantes excluyentes de disponibilidades o materiales acervos físicos finitos asfixiantes restrictivos exigiéndoles discriminaciones marginales incesantes renunciamientos y priorizaciones."),
            ("Costo de Oportunidad", "El destilado y purgado verdadero valor puro económico inmenso no del tributo físico adquirido sino de la rentabilidad disfrute utilitario y goces cumbres más eximios jerarquizados dolorosamente sacrificados descartados y sepultados invariablemente abortados intencionalmente y excluidos asimétrica ciegamente o desechados para materializar irrestrictamente consumar resolverse unilateralmente una dicotómica selección resolutiva marginal o acción excluyente de un camino decisivo de opción acaparadora prioritaria preferencial optante elegida escogida excluyente restrictiva."),
            ("Racionalidad Económica", "Arquetipo utilitarista homogeneizado axiomático de consistencia pura modelando a los seres sopesando calculadoramente asimétrica maximizador fríamente en el análisis perenne de utilidades vs tributos marginados marginalistas evaluando incrementos asintotales de beneficios colindantes o adyacentes de variaciones relativas transaccionales sin claudicaciones afectivas subyugadas o externalidades románticas pasionales caprichosas erráticas irracionales o alucinadas."),
            ("Equilibrio de Mercado", "Reposo matemático intersecto y clímax compensatorio y colofón resolutorio entre pujas traccionales excluyentes e inconciliables asimétricas de fuerzas e intereses disparejos y contradictorias diametrales contrapuestas (compras-ganancias) estabilizándose de liquidaciones o excedencias purificantes en el cuadrante P y Q de vaciamiento donde intenciones acaparadoras igualan empates y complacencias asintóticas totales plenas de los oferentes complaciendo las aspiracionales compradoras inelásticas exactas o precisas previsoras calibradas o mutuas simétricas equivalentes convergentes complacidas mutuas plenas de resoluciones exactas asimiladas congruentes en el vaciado pleno constante."),
            ("Curva de Demanda", "El sendero inverso correlacional exento o radiografía previsor estadística estipuladora psicológica de los menguantes o abismales sacrificios de renuncias y cuotas monetarias que muchedumbre consumidoras accederían o condescenderían y estipularían destilar abdicar escalonadamente decrecientes en precios ceteris paribus perdiendo e inclinándose marginalmente inelásticos al disponerse de dosis excedentarias adicionales decrecientes de bienes marginales escalonados redundantes atiborradores subyacentes descendentes decrecientes marginales abismales adicionales y redundantes en asimilaciones decadentes iteradas perennes continuadas iterativas sumadas.")
        ]
    },
    "mic2": {
        "color": "indigo",
        "title": "Glosario de Microeconomía",
        "concepts": [
            ("Preferencia Revelada", "Axioma praxeológico purista empirico destilado y sin asunciones utópicas metafísicas intangibles interiores neuropsicológicas inescrutables de cerebros ciegos dictaminando e infiriendo consistencias lógicas ordinales o rankings de jerarquizaciones inamovibles inescrutables basándose exclusivamente asimétrica rigurosa observablemente empírica o fáctica y contundentemente decodificable y rastreable empíricamente en las liquidaciones tangibles y billeteras de acciones facturadas transadas ejecutadas palpablemente innegables evidentes manifestadas o exhibidas o plasmadas accionales irrefutables materializadas operativas externas reales expuestas exteriorizadas o manifestadas fácticamente palpables."),
            ("Curva de Indiferencia", "Lugar geométrico o valle de nivel isocuántico isotensional sopesando combinatorias interrelacionadas compensatorias transaccionales de dos fungibles $x,y$ delineando e igualando o atemperando unívocamente empíricamente o conceptualmente idénticos colmados exultantes techos absolutos inestables inasibles idénticos escalafones o mesetas topográficas de goces orgánicos y utilidades y asimilables cumbres de euforia simétricas psicológicas constantes inmutables empáticas o satisfactores homólogos subyacentes de utilitarismos neutras para acaparadores y hedonismos puros estables inmutables del consumidor resolutivo neutral frente a permutaciones mutables compensatorias interinas equilibrantes asimilativas transitorias compensables asintóticas simétricas neutras."),
            ("Relación Marginal de Sustitución (RMS)", "Inclinación matemática y ratio fraccional o tangente de disposición claudicante compensable del dolor sustitutorio sopesable subjetiva sacrificable dictaminadora de la curva delineando exactamente cuántas e irrisorias o asimétricas fraccionales o enteras unidades fútiles de un satisfactor secundario $y$ condesciende claudicantemente y exige irrenunciable asintóticamente o compensante resignativo abdicar por acaparar marginal interfecto o inyectivo infinitesimal adicional del factor central predilecto unitario primario $x$ sin trastocar o devaluar su umbral empírico topográfico orgánico absoluto y estandar inamovible de idéntica plenitud isotópica incesante neutral inmutable idéntica preestablecida utilitaria o goce inestable basal pre-fijado neutral inafectado inalteable conservando invariable clímax."),
            ("Restricción Presupuestaria", "Muro inescrutable y arista aritmética de contención o clausura de fronteras infranqueables del vector dictatorial opresor excluyente contable de posibilidades de billetera anclando e inexorable delimitante cercenante y tajante estipulado asimétricamente de adquisiciones tangibles asumiendo e invirtiendo limitadas incondicionales rentas preasignadas deudoras finitas o bolsillos ingresos preestablecidos dados enfrentadas forzosamente en las combinatorias aditivas tasables transaccionales imponderables unitarias fraccionales por el régimen de etiquetados pre-asignados o escalafones del sistema mercado inelásticos exógenamente determinantes coercitivos limitantes dictaminados abisales nominalizados transables coartadores tasadores externos inobjetables objetivos fríos invariables restrictivos infranqueables inamovibles asintóticos."),
            ("Óptimo del Consumidor", "Intersección clímax euclídeo y cenit utilitarista tangente de coincidencia suprema de vaciamiento equilibrador donde el ratio de sacrificio sopesable individual asimétrico inmutable caprichoso y anhelo biológico (RMS) acopla matemáticamente clona irrestrictamente abraza comulgando y empatando milimétricamente el ratio inflexible de canje dictatorial o tasa marginal objetiva exógena inescrutable exterior transmutatoria de precios impuestos subyugador del mercado $(P_x/P_y)$ maximizando en tope eclosión coronada asintótica plena el límite superior máximo inelástico coronador factible del contorno adquisitivo fraccional delimitado presupuesto basal de frontera disponible estricta fraccional totalizante absoluta suprema alcanzable cumbre resolutiva.")
        ]
    },
    "mic3": {
        "color": "indigo",
        "title": "Glosario de Microeconomía",
        "concepts": [
            ("Efecto Sustitución", "Migración táctica u órbita compensatoria resolutiva asimilativa defensiva estricta de migración predileccional o resguardo hacia horizontes o bienes abaratados homólogos en detrimento purificador descartable e intercamio asintomático del abaratado descartando lo encarecido colindante ante mutaciones del vector exógeno $P$, simulando abstracciones exentas destiladas aisladas o purificando teóricamente sin injerencias aditivas colaterales mutativas e impurezas empobrecedoras simultáneas previsoras compensatorias inamovibles congeladoras pre-estabilizadoras y restitutivas de ingresos idénticos subyacentes compensaciones hicksianas utilitarias del umbral neutro inobjetable irreal basal pre-establecido de utilidad anclada o invariable compensada inamovible."),
            ("Efecto Renta", "Secuela macro colateral empobrecedora implícita o inyección puramente empujada de empoderamiento adquisitorio colindante indirecta virtual subyugante paralela o residual transaccional emanante y residual subproducente colateral e inintencionada adyacente inercial transicional de cualquier vaivén fluctuacional de encarecimientos $P$, donde el mismo estático e inamovible y crudo estanco cheque o bolsa nominal de salarios pre-asignada inamovible acusa y devela perversas depreciativas asfixiantes licuadoras caídas o rebosantes asimétricas exultantes excedentarias dilataciones ficticias del caudal fáctico transable palpable fraccional poder real de apropiaciones en el mundo físico de cuotas unitarias crudas palpadoras adquisitorias subyacentes."),
            ("Bien Normal", "Estructura ontológica mercantil o catálogo resolutivo predeterminado cuya elástica propensión correlativa estadística asimila subyugadamente sin rebeldías empujes ascendentes demandantes ávidos colaterales emparejados alineados paralelos inescrutables correspondientes ante empoderamientos u óbolos e inyecciones de incrementales sustanciosas u opulencias abultadas de tesoros bolsillos o alzas dotacionales de haberes de ingresos engrosando alicientes pre-ordenados $I \\uparrow \\implies Q \\uparrow$."),
            ("Bien Inferior", "Clasificación paradójica contraintuitiva pero recurrente empírica de productos estigmatizables arcaicos vulgares rudimentarios menesterosos de pobrezas o calidades empobrecidas degradadas sustituibles cuya ansia o apetito estadístico asimétrico consumidor se disuelve extinguiendo descarta expulsa en picada trágicamente o reduce en fuga repelente o exilios compensadores repudios asimétricos marginantes decrece $Q \\downarrow$ a expensas compensadas o en la eventualidad de riquezas o empujes fortificados rentísticos enriquecedores opulencias bonanzas ascendentes empoderamientos bolsillos engrosados ascendentes aliviadores $I \\uparrow$."),
            ("Bien Giffen", "Quimera teórica estrafalaria anómala insólita exótica inaudita irrestricta o atipicidad estadística abismalmente contra-teórica paradojal incomprensible irlandesa patológica rarísima donde la pre-ordenanza o propensión invertida destrozando simetrías clásicas de lógicas de curva $D$ estipula absurdamente inverosímil subyugante y demencialmente alicientes devoradores correlativos inescrutables de $Q \\uparrow$ si casualidades exógenas perversas elevan asfixiantes asoladores encareciendo letales agudas los índices de valores tasadores $P \\uparrow$. Esto por el devastador y canibalizador ultra-efecto abismal empobrecedor rentístico asimilador colosal letal asfixiador acaparador aniquilador de pauperización crudo inmanente extremo hiperempobrecedor asimétrico inmenso abrumador que opaca al sustitutorio inoperante e inferior hipertrofiado superándolo opacándolo avasallándolo eclipsante aniquilando excedentario superatriz aplastante insoslayable absorbente inusitado.")
        ]
    },
    "mic4": {
        "color": "indigo",
        "title": "Glosario de Microeconomía",
        "concepts": [
            ("Largo Plazo", "Dimensión y horizonte espectral teórico conceptual irreal analítico resolutivo no temporal de exenciones sin anclajes ineludibles forzados inmutables asfixiantes pegajosos fijos o pre-estatuídos crónicos inflexibles o irrevocables. Dimensión emancipadora exenta y transitable sin nudos ni ataduras infraestructurales donde enteramente omnímodamente todos y en sumatoria amalgamada total e impolutos la universalidad completa de insumos factores basales originarios preasignados asimétricos constantes ($K, L, etc$) devienen, licuan, metamorfosean transustancian y transmutan en maleabilidad elástica sin restricciones y mutabilidades mudables variables acopladas escalables plásticas adaptables expandibles contraíbles al unísono."),
            ("Corto Plazo", "Limitante cronológico infranqueable empírico constringente asfixiante emparedador amurallado transicional o subyugante e interino dictaminador restrictivo y coartador resolutivo donde en su seno el emprendedor experimenta celdas o dogales insoldables inquebrantables estipulando e induciendo inexorable o irrevocables ciegos invariables estamentos productivistas colosales constantes en que, al menos insalvablemente, uno o múltiples enraizados de sus aristas basales troncales originarias dotacionales o infraestructurales pesados ($K$ tierra hornos matrices fijas) yace irrevocablemente petrificado estático inamovible fijos atascado congelado paralizado inabordables en inmutabilidad inelástica ciega imposibilitado a licuarse acomodarse modificarse desinvertirse o expandirse forzando distorsivos estrangulamientos en los reacomodos pre-ordenados."),
            ("Costo Marginal", "Acentuación o diferencial purificado extra derivativo puritano delta exógeno aditivo adicional adyacente infinitesimal unitario asimétrico contable extra compensante colindante recargable aditivo puramente incrementado sobre los acumulados incurridos pasivos originarios arrojando el excedente exacto y alícuota sobreesfuerzo punitivo asimétrico devengable o sangría inyectable asimétrica erogable o desangrante del bolsillo excedentario y drenante que cuesta y penaliza asimétrica adicional unitario manufacturar o producir fabricando y eyectando un solo pre-engrane unitario originario infinitesimal adyacente o estipulado ítem fraccional o pieza indivisible excedente posterior subsiguiente adicional pre marginal extra purificado adicionalizado exacto infinitesimal subyacente subsiguiente."),
            ("Costo Medio", "Ratio dispersor u homogenizador estadístico prorrateado llanamente globalizado asimétrico distributivo global amortiguador donde universalidades agregativas de bolsas punitivas pasivas globales de gastos, tanto irrenunciables pesados abismales estáticos $CF$ como maleables $CV$, son derramados llanamente esparcidos atenuadamente recayendo en la dilución fraccionada divisoria y prorrateable aritmética distributivamente y de media per cápita equitativa por sobre abultadas numeraciones crudas inmensas fraccionarias acopiadoras estipuladas cuantificadas de la globalidad volumen manufacturado extraído eyectado Q de ítems eyectados preestablecidos extraídos prefigurados fabricados extraídos totales prorrateados."),
            ("Retornos Decrecientes", "Cicatriz implacable de ineficiencias entrópicas de la naturaleza estigmatizante en aglomeraciones o hacinamientos asimétricos operarios constringidos subyugados perversos ineficientes productivos empíricos e inescrutables de fatalidades organizativas físicas subyacentes. Cuando asfixiados en corralitos fijos $K$, adiciones sobrecargantes excesivas agigantadas de nóminas jornaleras atiborradoras de peones incesantes $L$ aportan asimétricas insignificancias menguantes insignificantes declinantes irrelevantes excedentarias puras irrisorias diluidas o efímeras de productos unitarios colindantes adicionales fraccionales adicionales e infinitesimales de volumen declinante irrisorio abismales descendentes $PMg$ mermantes abismales minúsculos decadentes y eventualmente asintóticos y contraproducentes o nulificantes obstruccionistas residuales restativos inoperantes y nulos e insignificantes inanes o caducos decrecientes menguantes reducidos irrisorios ínfimos restativos en incesantes adicionales diluidos en atascos asfixiantes espurios.")
        ]
    },
    "mic5": {
        "color": "indigo",
        "title": "Glosario de Microeconomía",
        "concepts": [
            ("Competencia Perfecta", "Arcadia irreal o abstracción teórica inmaculada paramétrica u utópico modelo extremo polar idealizado inencontrable prístino inorgánico. Donde atomizaciones e infinitos y plenos agentes innumerables microscópicos imperceptibles anónimos transan exentos de barreras y permeables irrestrictos permeados de trasparencias informativas holísticas incondicionales omniscientes absolutas en rubros y tipologías hiper-homogeneizadas clónicas espejadas e indistinguibles desprovistos y carentes o abortados asintomáticos absolutamente nulos en su total impericia imposibilidad inútil o insignificancia traccional microscópica para poder incidir desviar adulterar sesgar inyectar de empujes coactivos monopolizadores encarecientes o distorsiona e imponer y dominar o afectar coaccionar ínfimamente o imperceptible exógenamente y manipular los dictámenes imperturbables macro-estructurales del vaciamiento fijado o inescrutables asintóticos del precio imperante general rector regidor sistémico exógeno mercado subyugante dado exógeno dictatorial asimilable transable absoluto y unánime único y constante dictado por designios en red inescrutables del ecosistema impersonalizado dado exteriorizado inamovible pasivo tomado impositivo exógeno impersonal dictado por confluencia global inalienable de red inasible atomizada paramétrica."),
            ("Precio-Aceptante", "Indefensión perenne, obediencia estructural sumisa, claudicación de estamentos de poder inescrutable y subyugación fatal irreversible para los menesterosos competidores operarios atomizados minúsculos subyugados de carteles irreales. Unánimemente y coercitivamente ceden e internalizan adoptando subsumiendo ineludibles irremediables acatadores de pizarras externas el valor unitario de sus mercancías e inmodificables regidor subyugante transaccionable unipolar asfixiante colosal, en asimetría cega inmanente dictaminado inescrutablemente por vórtices irreductibles supremos inorgánicos del vaciamiento supremo exterior macro general agregado inalcanzable de equilibrio inexpugnable ajeno y distanciado e inmodificable irrefutable irremediable incontestable globalizado impersonal general dictatorial impersonal prefigurado exteriormente a sus acervos irrelevantes marginales ínfimos microscópicos infinitesimales nulos estériles e inofensivos de sus voluntades irrisorias insignificantes o frágiles poderíos mercantiles locales enclenques intrascendentes."),
            ("Ingreso Marginal", "Inyección y chorreadura infinitesimal fraccional transaccional acaparada extractiva facturable recaudatoria marginal delta purificada puritana excedentaria inyectiva aditiva cruda exógena adentrada marginal o suplementaria monetizada recibible o drenada devengable originaria estipulada neta al bolsillos acreedores incrementada agregativa por la mera colocación y desagotamiento de transar ofertar rematar inyectar de canje un ultimísimo rezagado posterior excedentario residual ítem y fraccional marginal empujado colindante y adicional o suplementario subyacente preestablecido adyacente infinitesimal manufacturado de unidad Q transable infinitesimal adyacente. En perfectas arcadias, este guarismo iguala calca simétrica exacta e irrestrictamente asintomática idéntica invariablemente en asimilación y fusión al congelado inamovible y dictaminado regidor valor tabulador estatuido imperturbable exógeno precio P rector externo dado ($IMg=P$) asintótica e irreductiblemente inelástico inmutable fijo imperante y dictatorial impositivo paralizador pasivo y dictaminado."),
            ("Monopolio", "Absolutismo, cúpula y realeza imperialista mercantil subyugante opresora inorgánica y concentrada. Entronación unilateral asfixiante excluyente única hermética solitaria estigmatizante desarticulando redes donde un único agente acaparador exclusivista inexpugnable domina tiraniza ejerce sojuzgación imperiosa extorsionante hegemónicamente prebendarizadora y desproveída blindada amurallada exenta de cercos competenciales homólogos asfixiando amenazas expoliantes sustitutores de suplentes desérticos y exentos alternativos viables carente u opresora absoluta del suministro general y global de los rubros ineludibles originarios transables prefigurados de demandas asoladas forzosas cautivas inelásticas subsumibles resignadas e inexcusables atadas sin salidas subyugadas e inelásticas desproveídas alternativas acorraladas y rehenes."),
            ("Pérdida Irrecuperable (Peso Muerto)", "Sangría macro, socavón, incineración disipativa inmaterial inaudita o desgarro estéril desaprovechable social deflacionaria aniquilante vaporizador o amputación colosal expropiada fútil evaporada mutilante e incinerada sin asimiladores de redistribución de excedencias originarias y mutiladas esfumadas o de socavones de gozos frustrados abismales extirpaciones aniquilador incalculables esfumados vaporizados purificados volatilizando rentas predispuestas colindantes conjuntas irradicables o excedentes de transacciones truncas abortadas sin concretar ahogando sin nacer y estéril disueltos irrenunciables asimilables que evaporan rentas y disfrutes frustrando utilidades irrefutable irreemplazables y conjuntas no asimilables a ganadores aniquilando suma cero ineficiente asimétrica letal y destructiva generadas trágica asfixiada asimétrica e inexorables colosales irremediables e inocuas fútiles evaporadas exógenadamente y aniquiladas asoladoras estancadoras abismadoramente letárgicas puritanamente destructivas e insolucionables crónicas generadas colosalmente por extralimitaciones fijadoras monopolistas (donde P encastrado punitivo acaparador supera abismadoramente o disuade y castiga e intersecta superlativo marginal asimétricamente disuadiendo por sobre Cmg estipulativo de eficiencias limitantes coartando marginando transacciones desahuciadas o estranguladas expeliendo del ecosistema subyacente consumos factibles mutuamente idóneos benéficos y coartadoramente frustrantes irrecuperables asintóticos truncados abortados irredimibles evaporadas irrecuperables extirpados).")
        ]
    }
}

def inject_glossaries():
    for mod, data in GLOSSARIES.items():
        filepath = f"/Users/machd/Desktop/licecon/web-portal/public/program/{mod}.md"
        if not os.path.exists(filepath):
            print(f"File not found: {filepath}")
            continue

        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        if "<!-- GLOSARIO -->" in content:
            print(f"Glossary already exists in {mod}")
            continue

        color = data["color"]
        
        # Build HTML
        html = f'<!-- GLOSARIO -->\n<section class="mb-24">\n    <div class="flex items-center gap-3 mb-10">\n        <span class="text-{color}-500 font-mono text-xs">[GL]</span>\n        <h2 class="text-white font-black text-2xl uppercase tracking-tighter">{data["title"]}</h2>\n    </div>\n    <div class="space-y-3">\n'
        
        for term, desc in data["concepts"]:
            term_esc = term.replace('\\', '\\\\')
            desc_esc = desc.replace('\\', '\\\\')
            html += f'''        <div class="flex gap-4 p-5 bg-white/3 border border-white/8 rounded-2xl hover:bg-white/5 transition-colors">
            <span class="text-{color}-500 font-mono font-black text-[10px] uppercase tracking-widest min-w-[150px] pt-0.5">{term_esc}</span>
            <p class="text-slate-400 text-sm leading-relaxed">{desc_esc}</p>
        </div>\n'''
        
        html += '    </div>\n</section>\n\n'

        target = "<!-- FOOTER -->"
        if target in content:
            content = content.replace(target, html + target)
        else:
            content = re.sub(r'(</div>\s*</div>\s*)$', html + r'\1', content)
            
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
            
        print(f"Injected glossary into {mod}")

if __name__ == "__main__":
    inject_glossaries()
